In [42]:
import cv2
import numpy as np
import matplotlib
import math
from matplotlib import pyplot as plt
%matplotlib inline  

In [61]:
images_name = ['./imgs/target.jpg']
images = []
for img_name in images_name:
    img = cv2.imread(img_name)
    images.append(img)

imgpoints = ([2270, 883],
            [2402, 910],
            [2532, 931],
            [2284, 1060],
            [2414, 1082],
            [2541, 1101],
            [2293, 1242],
            [2425, 1258],
            [2553, 1270],
            [2304, 1430],
            [2438, 1436],
            [2567, 1444],
            [2320, 1617],
            [2455, 1619],
            [2582, 1620],
            [1938, 907],
            [1825, 950],
            [1714, 989],
            [1551, 1086],
            [1835, 1123],
            [1725, 1155],
            [1956, 1270],
            [1846, 1299],
            [1735, 1329],
            [1963, 1457],
            [1849, 1479],
            [1737, 1501]
            )
# worldpoints = ([0,0,0],
#             [20,0,0],
#             [40,0,0],
#             [0,20,0],
#             [20,20,0],
#             [40,20,0],
#             [0,40,0],
#             [20,40,0],
#             [40,40,0],
#             [0,60,0],
#             [20,60,0],
#             [40,60,0],
#             [0,80,0],
#             [20,80,0],
#             [40,80,0],
#             [-27.2,0,-24.5],
#             [-27.2,0,-44.5],
#             [-27.2,0,-64.5],
#             [-27.2,20,-24.5],
#             [-27.2,20,-44.5],
#             [-27.2,20,-64.5],
#             [-27.2,40,-24.5],
#             [-27.2,40,-44.5],
#             [-27.2,40,-64.5],
#             [-27.2,60,-24.5],
#             [-27.2,60,-44.5],
#             [-27.2,60,-64.5])

worldpoints = ([27.2,0,80],
            [47.2,0,80],
            [67.2,0,80],
            [27.2,0,60],
            [47.2,0,60],
            [67.2,0,60],
            [27.2,0,40],
            [47.2,0,40],
            [67.2,0,40],
            [27.2,0,20],
            [47.2,0,20],
            [67.2,0,20],
            [27.2,0,0],
            [47.2,0,0],
            [67.2,0,0],
            [0,24.5,80],
            [0,44.5,80],
            [0,64.5,80],
            [0,24.5,60],
            [0,44.5,60],
            [0,64.5,60],
            [0,24.5,40],
            [0,44.5,40],
            [0,64.5,40],
            [0,24.5,20],
            [0,44.5,20],
            [0,64.5,20]
              )

worldpoints = np.asarray(worldpoints)
# cv2.circle(images[0],(imgpoints[0][0],imgpoints[0][1]),50,(0,0,255),-1)#0,0
# cv2.putText(images[0],str(worldpoints[0]),(imgpoints[0][0],imgpoints[0][1]), cv2.FONT_HERSHEY_SIMPLEX, 5,(0,0,255),15,cv2.LINE_AA)
# cv2.circle(images[0],(imgpoints[-1][0],imgpoints[-1][1]),50,(255,0,0),-1)#fim,fim
# cv2.circle(images[0],(imgpoints[14][0],imgpoints[14][1]),50,(0,0,255),-1)#0,0
# cv2.circle(images[0],(imgpoints[15][0],imgpoints[15][1]),50,(255,0,0),-1)#fim,fim
# cv2.putText(images[0],str(worldpoints[-1]),(imgpoints[-1][0],imgpoints[-1][1]), cv2.FONT_HERSHEY_SIMPLEX, 5,(0,0,255),15,cv2.LINE_AA)
# plt.imshow(cv2.cvtColor(images[0], cv2.COLOR_BGR2RGB))
# plt.show()

In [62]:
A = []
for worldpoint, imagepoint in zip(worldpoints, imgpoints):
    print(worldpoint, imagepoint)
    A_line = []
    A_line.append(imagepoint[0] * worldpoint[0])
    A_line.append(imagepoint[0] * worldpoint[1])
    A_line.append(imagepoint[0] * worldpoint[2])
    A_line.append(imagepoint[0])
    A_line.append(-imagepoint[1] * worldpoint[0])
    A_line.append(-imagepoint[1] * worldpoint[1])
    A_line.append(-imagepoint[1] * worldpoint[2])
    A_line.append(-imagepoint[1])
    A.append(A_line)
A = np.asarray(A)


[27.2  0.  80. ] [2270, 883]
[47.2  0.  80. ] [2402, 910]
[67.2  0.  80. ] [2532, 931]
[27.2  0.  60. ] [2284, 1060]
[47.2  0.  60. ] [2414, 1082]
[67.2  0.  60. ] [2541, 1101]
[27.2  0.  40. ] [2293, 1242]
[47.2  0.  40. ] [2425, 1258]
[67.2  0.  40. ] [2553, 1270]
[27.2  0.  20. ] [2304, 1430]
[47.2  0.  20. ] [2438, 1436]
[67.2  0.  20. ] [2567, 1444]
[27.2  0.   0. ] [2320, 1617]
[47.2  0.   0. ] [2455, 1619]
[67.2  0.   0. ] [2582, 1620]
[ 0.  24.5 80. ] [1938, 907]
[ 0.  44.5 80. ] [1825, 950]
[ 0.  64.5 80. ] [1714, 989]
[ 0.  24.5 60. ] [1551, 1086]
[ 0.  44.5 60. ] [1835, 1123]
[ 0.  64.5 60. ] [1725, 1155]
[ 0.  24.5 40. ] [1956, 1270]
[ 0.  44.5 40. ] [1846, 1299]
[ 0.  64.5 40. ] [1735, 1329]
[ 0.  24.5 20. ] [1963, 1457]
[ 0.  44.5 20. ] [1849, 1479]
[ 0.  64.5 20. ] [1737, 1501]


In [74]:
U, D, V = np.linalg.svd(A, full_matrices=True)
# print(np.transpose(V))
# print(D)
# print (U.shape, D.shape, V.shape)
# print(np.linalg.eig(A))
# print(np.linalg.matrix_rank(A))
minSingValue = np.argmin(D)
print(D)
V_selected = V[minSingValue]
for idx, v in enumerate(V):
    print ("V[{}]".format(idx))
    print(np.dot(A, v))

# print(V,V_selected)

[7.60814509e+05 4.41144156e+05 2.26315500e+05 3.95379474e+04
 2.44647456e+04 1.72155831e+04 2.27077420e+03 1.37017087e+02]
V[0]
[-192195.65563953 -231588.01706422 -273498.84278209 -159203.35217405
 -197231.74386414 -237793.65598996 -123237.53866314 -160187.9903415
 -199624.42827156  -84620.27841236 -120494.69931931 -158975.01307964
  -43135.46642413  -78107.27772882 -115571.22686518 -147149.29078002
 -150037.45623931 -152328.97650122  -99015.68019046 -122277.19459739
 -126173.15398726  -85656.62225425  -91917.08047448  -97522.96540574
  -50752.44186097  -58664.58966308  -65932.24045251]
V[1]
[  19405.54787949  -15771.91630181  -54531.56064951    3535.21359116
  -33837.61250588  -74642.68360041  -13987.38396054  -53527.27612558
  -96392.75643252  -33226.9648583   -74923.41537341 -119894.74639026
  -54280.35993734  -98192.45566548 -145136.13451711   90566.60470027
  112653.23651114  133000.38297325   68334.3793599   103605.11712093
  125495.58153009   67648.15195833   93063.75386496  116

In [66]:
gamma = math.sqrt((V_selected[0]**2)+(V_selected[1]**2)+(V_selected[2]**2))
alfa = math.sqrt((V_selected[4]**2)+(V_selected[5]**2)+(V_selected[6]**2))/gamma
print (gamma,alfa)

0.004443992625443208 1.1458782593595662


In [67]:
r = np.ones(shape=(3,3))
t = np.ones(shape=(3,1))
r[1][0] = V_selected[0]/gamma
r[1][1] = V_selected[1]/gamma
r[1][2] = V_selected[2]/gamma
t[1] = V_selected[3]/gamma
r[0][0] = (V_selected[4]/alfa)/gamma
r[0][1] = (V_selected[5]/alfa)/gamma
r[0][2] = (V_selected[6]/alfa)/gamma
t[0] = (V_selected[7]/alfa)/gamma


In [68]:
r[2,:] = np.cross(r[0,:],r[1,:])

u,d,v = np.linalg.svd(r, full_matrices=True, compute_uv=True)
r = np.dot(np.dot(u,np.identity(3)),v)
print (r)
print (gamma,(gamma**2 *(r[1][0]**2 + r[1][1]**2 + r[1][2]**2)) ** (1/2),gamma ==(gamma**2 *(r[1][0]**2 + r[1][1]**2 + r[1][2]**2)) ** (1/2))
print (alfa*gamma,(alfa**2 *gamma**2 *(r[0][0]**2 + r[0][1]**2 + r[0][2]**2)) ** (1/2),alfa*gamma==(alfa**2*gamma**2 *(r[0][0]**2 + r[0][1]**2 + r[0][2]**2)) ** (1/2))
print (r[1][0]**2+r[1][1]**2+r[1][2]**2)
print (r[0][0]**2+r[0][1]**2+r[0][2]**2)
print (r[2][0]**2+r[2][1]**2+r[2][2]**2)
print("******************")
print (np.inner(r[2,:],r[0,:]),np.inner(r[2,:],r[1,:])) 
print("******************")
print (t)

[[-0.74984114  0.62210228  0.22522659]
 [ 0.14711177 -0.17512573  0.97349325]
 [ 0.64505534  0.76309877  0.03979791]]
0.004443992625443208 0.004443992625443207 False
0.005092274534249612 0.0050922745342496115 False
0.9999999999999996
0.9999999999999998
0.9999999999999997
******************
5.325601071248798e-16 -6.245004513516506e-17
******************
[[-157.46510292]
 [-134.44660607]
 [   1.        ]]


In [69]:
x_aux = imgpoints[1][0] * (r[0][0] * worldpoints[1][0] + r[0][1] * worldpoints[1][1] +
                                    r[0][2] * worldpoints[1][2] + t[0])

# print(x_aux,imgpoints[0][1][0][0],worldpoints[0][1],imgpoints[0][1][0][1] )
if x_aux > 0:
    r[0,:] = -r[0,:]
    r[1,:] = -r[1,:]
    t[0:2] = -t[0:2]

A_2 = []
# for worldpoint_vector,imgpoints_vector in zip(worldpoints,imgpoints):
for worldpoint,imgpoint in zip(worldpoints,imgpoints):
    A_line = []
    A_line.append(imgpoint[0])
    A_line.append(r[0][0] * worldpoint[0] + r[0][1] * worldpoint[1] + r[0][2] * worldpoint[2] + t[0][0])
    A_2.append(A_line)

A_2 = np.asarray(A_2)
# print (A_2.shape)
b = []
# for worldpoint_vector,imgpoints_vector in zip(worldpoints,imgpoints):
for worldpoint,imgpoint in zip(worldpoints,imgpoints):
        b.append(-imgpoint[0]* (r[2][0] * worldpoint[0] + r[2][1] * worldpoint[1] + r[2][2] * worldpoint[2]))

b = np.asarray(b)
# t[0][0]

In [72]:
tf = np.dot(np.linalg.pinv(A_2),b)
# c = A_2[1][0]*tz+A_2[1][1]*fx
c = np.dot(A_2[2],tf)
# print (c,b[1],c/b[1],c*(b[1]/c),b[1])
c = c/b[2]
print(c,tf/c)

0.7121828011047378 [ -69.58063626 -307.42425595]
